
! (B) ONE-DIMENSIONAL DERIVATIVE-FREE QUADRATIC SEARCH FOR A POSITIVE
!     LOCAL MINIMUM
!
! (SUBPROGRAMS INVOLVED:  SEARSL, FNSET (USER SUPPLIED), ILOC, D1MACH,
! ERCMP1, RCHMOD, CORRCT, SEARCR, MULLER, WOLFE, CONENR, HOUSE,
! DOTPRD, REFWL;  ONLY THE FIRST FIVE OF THESE ARE ACTUALLY USED)
!
! GIVEN A FUNCTION F OF ONE VARIABLE (WHERE F(X) IS COMPUTED IN SUBROUTINE
! FNSET AS CONFUN(1,1), WITH X = PARAM(1)) AND A POSITIVE NUMBER PROJCT,
! THE PROGRAM WILL ATTEMPT TO LOCATE A NEW PROJCT WITH EMIN = F(PROJCT),
! WITH THE NEW PROJCT APPROXIMATELY GIVING A LOCAL MINIMUM OF F IN
! [(OLD PROJCT)/1024, 1024*(OLD PROJCT)].  IF IT FAILS TO DO THIS, THE
! PROGRAM WILL RETURN WITH PROJCT = THE ABSCISSA FOUND WITH SMALLEST
! EMIN = F(PROJCT).  ON OUTPUT, NSRCH WILL BE THE NUMBER OF EVALUATIONS
! OF F THAT WERE DONE.  THE SOLUTION PROCEDURE IS A MODIFICATION OF THE
! FOLLOWING:  COMPUTE F(PROJCT/2), F(PROJCT), AND F(2*PROJCT), IF THE
! CONDITIONS F(MIDDLE POINT) .LE. F(LEFT POINT) AND F(MIDDLE POINT) .LE.
! F(RIGHT POINT) ARE NOT BOTH SATISFIED THEN TRY TO GET THIS BY COMPUTING
! F AT SMALLER (OR LARGER) POINTS AT MOST 3 MORE TIMES;  ONCE THE
! CONDITIONS ARE SATISFIED, ASSUMING THE POINTS ARE NOT TOO CLOSE TO BEING
! COLLINEAR, PASS A QUADRATIC POLYNOMIAL THROUGH THE THREE POINTS AND USE
! ITS UNIQUE MINIMUM IN THE INTERVAL TO REPLACE ONE OF THE ENDPOINTS WHILE
! MAINTAINING THE TWO CONDITIONS, CONTINUING UNTIL F HAS BEEN COMPUTED 4
! MORE TIMES OR THE INTERVAL LENGTH FALLS BELOW 100.0*B**(-ITT) OR THE
! POINTS BECOME NEARLY COLLINEAR.  THE FOLLOWING SAMPLE DRIVER AND
! SUBROUTINE FNSET ARE SET UP TO APPROXIMATE A SOLUTION OF THE LINE SEARCH
! PROBLEM OF MINIMIZING G((6.0D0,2.0D0) + PROJCT*(-2.0D0,-1.0D0)), WHERE
! G(U,V) = 3.0D0*ABS(U) + 2.0D0*ABS(V).  WE START WITH PROJCT = 1.0D0,
! THEN RUN THE PROGRAM AGAIN STARTING WITH THE RESULT OF THE FIRST RUN.
! (THE EXACT SOLUTION IS PROJCT = 3.0D0, EMIN = 2.0D0;  CONVERGENCE IS
! RATHER SLOW, MAINLY BECAUSE F IS NOT DIFFERENTIABLE AT THE MINIMUM.)
!
! SAMPLE DRIVER AND FNSET FOR (B) ONE-DIMENSIONAL SEARCH
 
      IMPLICIT NONE

      REAL*8 D1MACH , emin , emin1 , err1 , error , fun , param ,       &
           & parprj , parser , prjlim , projct , pttbl , spcmn , tol1 , &
           & tolcon , work , x
      INTEGER iact , iwork , nsrch
      DIMENSION x(2) , fun(1) , pttbl(1,1) , param(1) , error(4) ,      &
              & iact(1) , iwork(17) , work(42) , err1(4) , parprj(1) ,  &
              & parser(1)
      !OPEN (6,FILE='SEROUT')
      spcmn = D1MACH(3)
      tol1 = 100.0D0*spcmn
      tolcon = SQRT(spcmn)
      iact(1) = 1
      iwork(7) = 1
      prjlim = 1.0D0/spcmn
      param(1) = 0.0D0
      x(1) = 1.0D0
!*****BEGIN USER SETTABLE STATEMENTS 1 OF 2
      projct = 1.0D0
!*****END USER SETTABLE STATEMENTS 1 OF 2
      WRITE (6,99001) projct
99001 FORMAT (/' INITIALLY PROJCT IS',E22.13)
      CALL SEARSL(0,1,1,prjlim,tol1,x,fun,1,pttbl,1,1,param,error,2.0D0,&
                & 1,iact,0,1.0D0,tolcon,2.0D0,0,0,iwork,17,work,42,err1,&
                & parprj,projct,emin,emin1,parser,nsrch)
      WRITE (6,99002) projct , emin , nsrch
99002 FORMAT (/' AFTER SEARSL PROJCT IS',E22.13//' EMIN IS',E22.13,     &
             &'  NSRCH IS',I4)
      END
!*==FNSET.spg  processed by SPAG 6.72Dc at 18:12 on 18 Aug 2021
 
      SUBROUTINE FNSET(Nparm,Numgr,Pttbl,Iptb,Indm,Param,Ipt,Indfn,     &
                     & Icntyp,Confun)
      IMPLICIT NONE

      REAL*8 Confun , Param , Pttbl , u , v
      INTEGER Icntyp , Indfn , Indm , Ipt , Iptb , Nparm , Numgr
      DIMENSION Pttbl(Iptb,Indm) , Param(Nparm) , Icntyp(Numgr) ,       &
              & Confun(Numgr,Nparm+1)
!*****BEGIN USER SETTABLE STATEMENTS 2 OF 2
      u = 6.0D0 + Param(1)*(-2.0D0)
      v = 2.0D0 + Param(1)*(-1.0D0)
      Confun(1,1) = 3.0D0*ABS(u) + 2.0D0*ABS(v)
!*****END USER SETTABLE STATEMENTS 2 OF 2
      END
 
 
! OUTPUT 1 FOR (B) ONE-DIMENSIONAL SEARCH
!
! INITIALLY PROJCT IS   0.1000000000000E+01
!
! AFTER SEARSL PROJCT IS   0.2956250000000E+01
!
! EMIN IS   0.2175000000000E+01  NSRCH IS   8
!
! OUTPUT 2 FOR (B) ONE-DIMENSIONAL SEARCH
!
! INITIALLY PROJCT IS   0.2956250000000E+01
!
! AFTER SEARSL PROJCT IS   0.3010732751581E+01
!
! EMIN IS   0.2085862012645E+01  NSRCH IS   7
